# Generated by Django 6.1 on 2026-08-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('screensize', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mechanism', models.CharField(max_length=100)),
                ('water_resistant', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Watch',
                'verbose_name_plural': 'Watches',
            },
        ),
    ]
